# Use our own standard Python base image
FROM competition/base-python

# Copy the bot's source code into the image
COPY bots/space_filler_bot/bot.py .

# Set the default command to run the bot
# CMD ["./run.sh", "bot.py"]