# Use the full "bullseye" version of OpenJDK 17 instead of "slim".
# This version is larger but includes common tools like wget out-of-the-box.
FROM openjdk:17-bullseye

# Set the working directory
WORKDIR /app